; PlatformIO configuration for Printing Press Stepper Controller
[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = espidf
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_build.sdkconfig_defaults = sdkconfig.defaults
