#pragma once

/**
 * Stepper motor driver for ESP32 + HY DIV-268N-5A + Nema 23.
 *
 * Overview step pulses are generated by the esp32 rmt peripheral, which clocks
 * out waveforms from hardware without CPU involvement. Direction and enable
 * are driven by plain GPIO. Three custom RMT encoders (see rmt_encoder.h)
 * produce the pulse streams:
 *
 *   - accel_encoder   — S-curve ramp from start_speed_hz to max_speed_hz over
 *                       accel_steps pulses.
 *   - uniform_encoder — constant-rate pulses at max_speed_hz for a given step
 *                       count (or effectively unbounded for continuous).
 *   - decel_encoder   — S-curve ramp from max_speed_hz back to start_speed_hz
 *                       over accel_steps pulses (the accel encoder reversed).
 *
 * STATE MACHINE
 *
 * The driver tracks a stepper_state_t: IDLE -> ACCELERATING -> RUNNING ->
 * DECELERATING -> IDLE. Transitions between phases happen when the current RMT
 * transmission finishes. An ISR (on_trans_done) fires on completion and
 * releases a binary semaphore; a dedicated FreeRTOS task (stepper_state_task)
 * waits on that semaphore and kicks off the next phase. This keeps encoder
 * creation and rmt_transmit() calls out of ISR context.
 *
 *
 * MOTION MODES
 *
 *   - stepper_run_steps(n)      Fire n pulses at max_speed_hz, no ramping.
 *                               Used for short jogs.
 *   - stepper_run_profiled(n)   Fixed-distance move with accel -> uniform ->
 *                               decel. If n < 2*accel_steps, the ramps are
 *                               shortened in place by recreating the accel and
 *                               decel encoders with smaller accel_steps, then
 *                               restored to the configured value after the
 *                               move completes (handle_profiled_move_
 *                               completion()).
 *   - stepper_run_continuous()  Accelerate to max_speed_hz and stay there
 *                               until stepper_ramp_stop() (S-curve decel) or
 *                               stepper_stop() (immediate).
 *
 * Stopping a continuous or in-flight move requires aborting the currently
 * queued RMT transmission. abort_and_decelerate() does this by cycling
 * rmt_disable()/rmt_enable() on the channel, draining the done semaphore so
 * the ISR's pending give is discarded, and then queuing the decel encoder.
 *
 * CONCURRENCY
 *
 * All public API calls are serialized by api_mutex so the web
 * handlers, button task, and any other callers can share the driver safely.
 * The state field is marked volatile and written from both the ISR and the
 * state task. Changing motion parameters (stepper_set_motion_params) is only
 * allowed while IDLE, because it tears down and rebuilds all three encoders.
 *
 * SIGNAL INVERSION
 *
 * invert_signals in stepper_config_t flips the DIR and ENABLE
 * polarity for drivers that need it (e.g. ULN2003 breakout boards used during
 * bring-up). The HY DIV-268N-5A uses active-LOW enable with
 * invert_signals=false.
 *
 * COMPLETION CALLBACK
 *
 * stepper_set_move_done_callback() registers a function
 * that is invoked from the state task (not the ISR) when a profiled move
 * finishes. This is used by the endpoint/auto-feed logic to chain moves.
 */

#include "esp_err.h"
#include <stdbool.h>
#include <stdint.h>

typedef enum {
    STEPPER_DIR_FORWARD = 1,
    STEPPER_DIR_REVERSE = 0,
} stepper_dir_t;

typedef enum {
    STEPPER_STATE_IDLE = 0,
    STEPPER_STATE_ACCELERATING,
    STEPPER_STATE_RUNNING,
    STEPPER_STATE_DECELERATING,
} stepper_state_t;

typedef struct {
    int step_gpio;
    int dir_gpio;
    int enable_gpio;
    uint32_t resolution_hz;  // RMT resolution (1 MHz recommended)
    uint32_t pulse_ticks;    // Pulse high duration in RMT ticks
    bool     invert_signals; // Invert DIR and ENABLE for ULN2003
} stepper_config_t;

typedef struct {
    uint32_t max_speed_hz;    // Target speed (default 2000)
    uint32_t start_speed_hz;  // Ramp start speed (default 100)
    uint32_t accel_steps;     // Steps in acceleration ramp (default 200)
} stepper_motion_params_t;

/**
 * Initialize the stepper driver hardware (RMT channel, GPIO).
 */
esp_err_t stepper_init(const stepper_config_t *config);

/**
 * Enable the stepper driver (active LOW on ENABLE pin).
 */
esp_err_t stepper_enable(void);

/**
 * Disable the stepper driver (releases holding torque).
 */
esp_err_t stepper_disable(void);

/**
 * Set motor direction.
 */
esp_err_t stepper_set_direction(stepper_dir_t dir);

/**
 * Set motion parameters (speed, acceleration).
 */
esp_err_t stepper_set_motion_params(const stepper_motion_params_t *params);

/**
 * Get current motion parameters.
 */
const stepper_motion_params_t *stepper_get_motion_params(void);

/**
 * Run a specific number of steps at the configured max speed (no acceleration).
 */
esp_err_t stepper_run_steps(uint32_t steps);

/**
 * Run a specific number of steps with S-curve acceleration and deceleration.
 * Phases: accel (accel_steps) -> uniform (remaining) -> decel (accel_steps).
 * If total steps < 2*accel_steps, the ramps are shortened proportionally.
 */
esp_err_t stepper_run_profiled(uint32_t steps);

/**
 * Start continuous stepping with S-curve acceleration.
 * Motor accelerates to the configured max speed and runs until
 * stepper_ramp_stop() or stepper_stop().
 */
esp_err_t stepper_run_continuous(void);

/**
 * Decelerate to stop using S-curve profile.
 */
esp_err_t stepper_ramp_stop(void);

/**
 * Immediately stop pulse generation (no deceleration).
 */
esp_err_t stepper_stop(void);

/**
 * Check if the stepper is currently running.
 */
bool stepper_is_running(void);

/**
 * Check if the stepper driver is enabled (armed).
 */
bool stepper_is_enabled(void);

/**
 * Get the current stepper state.
 */
stepper_state_t stepper_get_state(void);

/**
 * Register a callback for when a profiled move completes.
 * Called from the stepper state task context (not ISR).
 */
typedef void (*stepper_move_done_cb_t)(void);
void stepper_set_move_done_callback(stepper_move_done_cb_t cb);
